name: Deploy in Github Pages
on: [push]
jobs:
  install-and-build:
    name: Install and Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: install deps and build
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: | 
          npm install
          npm run build
      - name: upload build
        uses: actions/upload-artifact@v3
        with:
          name: dist-directory
          path: dist
  deploy-in-github-pages:
    name: Deploy in Github Pages
    needs: install-and-build
    runs-on: ubuntu-latest
    permissions:
      pages: write      
      id-token: write 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: download build
        uses: actions/upload-artifact@v3
        with:
          name: dist-directory
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
